name: Upload binaries to release

on:
  release:
    types: [created]

jobs:
  release:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: u64viewer-linux_amd64
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            asset_name: u64viewer-linux_musl_amd64
            target: x86_64-unknown-linux-musl
          - os: macos-latest
            asset_name: u64viewer-darwin_amd64
            target: x86_64-apple-darwin
          - os: macos-latest
            asset_name: u64viewer-darwin_arm64
            target: aarch64-apple-darwin
          - os: windows-latest
            asset_name: u64viewer-windows_amd64
            target: x86_64-pc-windows-msvc
          - os: windows-latest
            asset_name: u64viewer-windows_arm64
            target: aarch64-pc-windows-msvc

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Set Cargo.toml version
        shell: bash
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          sed -i "s|version = \".*-git\"|version = \"${VERSION}\"|" Cargo.toml
          sed -i "s|version = \".*-git\"|version = \"${VERSION}\"|" Cargo.lock

      - if: matrix.os == 'ubuntu-latest'
        name: Install linux dependencies
        run: |
          sudo apt update
          sudo apt install libasound2-dev musl-tools -y

      - name: Build
        run: cargo build --release --locked --target ${{ matrix.target }}

      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: target/${{ matrix.target }}/release/u64viewer
          asset_name: ${{ matrix.asset_name }}
