name: Upload binaries to release

on:
  release:
    types: [created]

jobs:
  release:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: u64viewer-linux_amd64
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            asset_name: u64viewer-linux_musl_amd64
            target: x86_64-unknown-linux-musl
          - os: macos-latest
            asset_name: u64viewer-darwin_amd64
            target: x86_64-apple-darwin
          - os: macos-latest
            asset_name: u64viewer-darwin_arm64
            target: arm64-apple-darwin
          - os: windows-latest
            asset_name: u64viewer-windows_amd64
            target: x86_64-pc-windows-msvc
          - os: windows-latest
            asset_name: u64viewer-windows_arm64
            target: aarch64-pc-windows-msvc

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Set Cargo.toml version
        shell: bash
        env:
          RELEASE_TAG: ${{ github.ref }}
        run: |
          cargo install cargo-edit
          cargo set-version ${GITHUB_REF_NAME}

      - name: Build
        run: cargo build --release --locked --target ${{ matrix.target }}

      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: target/${{ matrix.target }}/release/u64viewer
          asset_name: ${{ matrix.asset_name }}
